# *-* coding: UTF-8 *-*
#-------------------------------------------------------------------------------
# Name:        role_numbers
# Purpose:     contains a dictionary of valid role numbers and other info
#
# Author:      egrimm
#
# Created:     23/01/2014
# Copyright:   (c) egrimm 2014
# Licence:     <your licence>
#-------------------------------------------------------------------------------

from collections import defaultdict

role_numbers = []

def insert_into_role_numbers(
    role_number,
    school_name,
    address1,
    address2,
    address3,
    country,
    aDict):
    if get_role_number(role_number, aDict) is None:
        aDict.append(dict(zip(['role_number',
            'school_name',
            'address1',
            'address2',
            'address3',
            'country'],
            [role_number, school_name, address1, address2, address3, country])))


def get_role_number(role_number, aDict=role_numbers):
    return next((item for item in aDict if item['role_number'] == role_number),
        None)


insert_into_role_numbers('12345', 'Countrywood', '', '', '', '', role_numbers)
insert_into_role_numbers('23456', 'Maplewood', '', '', '', '', role_numbers)
insert_into_role_numbers('34567', 'Silas Wood', '', '', '', '', role_numbers)
insert_into_role_numbers('45678', 'Stimson', '', '', '', '', role_numbers)
insert_into_role_numbers('56789', 'Huntington HS', '', '', '', '', role_numbers)

# note to self: put this in memcache!
insert_into_role_numbers('76082H', 'Abbey Community College', 'Abbey Rd.', 'Ferrybank', '', 'Waterford', role_numbers)
insert_into_role_numbers('76072E', 'Abbey Community College', 'Boyle Town', '', '', 'Roscommon', role_numbers)
insert_into_role_numbers('71180F', 'Abbey Vocational School', 'Donegal Town', '', '', 'Donegal', role_numbers)
insert_into_role_numbers('76097U', 'Adamstown Community College', 'Adamstown', 'Dublin 15', '', 'Dublin', role_numbers)
insert_into_role_numbers('60910F', 'Alexandra College', 'Milltown', 'Dublin 6', '', 'Dublin', role_numbers)
insert_into_role_numbers('71390Q', 'Archbishop McHale College', 'Dublin Rd.', 'Tuam', '', 'Galway', role_numbers)
insert_into_role_numbers('72530L', 'Ard Scoil Chiarain Naofa', 'Frederick St.', 'Clara', '', 'Offaly', role_numbers)
insert_into_role_numbers('64900W', 'Ard Scoil na nDeise', 'Convent Rd.', 'Dungarvan', '', 'Waterford', role_numbers)
insert_into_role_numbers('91441T', 'Ardee Community School', 'Ardee', '', '', 'Louth', role_numbers)
insert_into_role_numbers('76129H', 'Ardgillan Community College', 'Castlelands', 'Balbriggan', '', 'Dublin', role_numbers)
insert_into_role_numbers('60291D', 'Árdscoil La Salle', 'Raheny Rd.', 'Raheny', 'Dublin 5', 'Dublin', role_numbers)
insert_into_role_numbers('64290V', 'Ardscoil Mhuire', 'Corbally', 'Limerick City', '', 'Limerick City', role_numbers)
insert_into_role_numbers('62890M', 'Ardscoil Mhuire', 'Mackney', 'Ballinasloe', '', 'Galway', role_numbers)
insert_into_role_numbers('65320J', 'Árdscoil na mBráithre', 'Clonmel', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('68077S', 'Árdscoil na Trionóide', 'Rathstewart', 'Athy', '', 'Kildare', role_numbers)
insert_into_role_numbers('71710I', 'Ardscoil Phadraig', 'Granard', '', '', 'Longford', role_numbers)
insert_into_role_numbers('70730J', 'Ardscoil Rath Iomgháin', 'Rathangan', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('64201T', 'Ardscoil Ris', 'North Circular Rd.', 'Limerick City', '', 'Limerick City', role_numbers)
insert_into_role_numbers('60420L', 'Árdscoil Rís', 'Griffith Ave.', 'Dublin 9', '', 'Dublin', role_numbers)
insert_into_role_numbers('62050O', 'Árdscoil Uí Urmoltaigh', 'Bandon', '', '', 'Cork', role_numbers)
insert_into_role_numbers('61770U', 'Arklow C.B.S.', 'Coolgreaney Rd.', 'Arklow', '', 'Wicklow', role_numbers)
insert_into_role_numbers('70740M', 'Arklow Community College', 'Coolgreaney Rd.', 'Arklow', '', 'Wicklow', role_numbers)
insert_into_role_numbers('91495T', 'Ashbourne Community School', 'Deerpark', 'Ashbourne', '', 'Meath', role_numbers)
insert_into_role_numbers('81008W', 'Ashton School', 'Blackrock Rd.', 'Cork City', '', 'Cork City', role_numbers)
insert_into_role_numbers('60851P', 'Assumption Secondary School', 'Kilnamana Rd.', 'Walkinstown', 'Dublin 12', 'Dublin', role_numbers)
insert_into_role_numbers('91517D', 'Athboy Community School', 'Athboy', '', '', 'Meath', role_numbers)
insert_into_role_numbers('71410T', 'Athlone Community College', 'Retreat Rd.', 'Athlone', '', 'Westmeath', role_numbers)
insert_into_role_numbers('70650L', 'Athy Community College', 'Athy', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('70810H', 'Avondale Community College', 'Rathdrum', '', '', 'Wicklow', role_numbers)
insert_into_role_numbers('91351S', 'Bailieborough Community School', 'Bailieborough', '', '', 'Cavan', role_numbers)
insert_into_role_numbers('70010V', 'Balbriggan Community College', 'Pine Ridge', 'Chapel St.', 'Balbriggan', 'Dublin', role_numbers)
insert_into_role_numbers('64500G', 'Balla Secondary School', 'Balla', 'Castlebar', '', 'Mayo', role_numbers)
insert_into_role_numbers('63460P', 'Ballinamore P.P.S.', 'Ballinamore', '', '', 'Leitrim', role_numbers)
insert_into_role_numbers('91386O', 'Ballincollig Community School', 'Innishmore', 'Ballincollig', '', 'Cork', role_numbers)
insert_into_role_numbers('72360M', 'Ballinode College', 'Clarion Rd.', 'Sligo Town', '', 'Sligo', role_numbers)
insert_into_role_numbers('91462E', 'Ballinrobe Community School', 'Convent Rd.', 'Ballinrobe', '', 'Mayo', role_numbers)
insert_into_role_numbers('91305L', 'Ballinteer Community School', 'Ballinteer', 'Dublin 16', '', 'Dublin', role_numbers)
insert_into_role_numbers('72170H', 'Ballybay Community College', 'Ballybay', '', '', 'Monaghan', role_numbers)
insert_into_role_numbers('91461C', 'Ballyhaunis Community School', 'Knock Rd.', 'Ballyhaunis', '', 'Mayo', role_numbers)
insert_into_role_numbers('71690F', 'Ballymahon Vocational School', 'Ballymahon', '', '', 'Longford', role_numbers)
insert_into_role_numbers('62060R', 'Bandon Grammar School', 'Bandon', '', '', 'Cork', role_numbers)
insert_into_role_numbers('76090G', 'Bantry Community College', 'Main St.', 'Bantry', '', 'Cork', role_numbers)
insert_into_role_numbers('91387Q', 'Beara Community School', 'Castletownbere', 'Beara', '', 'Cork', role_numbers)
insert_into_role_numbers('72010I', 'Beaufort College', 'Trim Rd.', 'Navan', '', 'Meath', role_numbers)
insert_into_role_numbers('72210Q', 'Beech Hill College', 'Monaghan Town', '', '', 'Monaghan', role_numbers)
insert_into_role_numbers('60520P', 'Belvedere College', '6 Great Denmark St.', 'Dublin 1', '', 'Dublin', role_numbers)
insert_into_role_numbers('60511O', 'Beneavin de la Salle College', 'Beneavin Rd.', 'Finglas', 'Dublin 11', 'Dublin', role_numbers)
insert_into_role_numbers('91397T', 'Bishopstown Community School', 'Westgate Rd.', 'Bishopstown', '', 'Cork', role_numbers)
insert_into_role_numbers('60030V', 'Blackrock College', 'Blackrock', '', '', 'Dublin', role_numbers)
insert_into_role_numbers('91509E', 'Blackwater Community School', 'Ballyanchor Rd.', 'Lismore', '', 'Waterford', role_numbers)
insert_into_role_numbers('91316Q', 'Blakestown Community School', 'Blanchardstown', 'Dublin 15', '', 'Dublin', role_numbers)
insert_into_role_numbers('70760S', 'Blessington Community College', 'Naas Rd.', 'Blessington', '', 'Wicklow', role_numbers)
insert_into_role_numbers('81009B', 'Boherbue Comprehensive School', 'Boherbue', 'Mallow', '', 'Cork', role_numbers)
insert_into_role_numbers('70400L', 'Borris Vocational School', 'Borris', '', '', 'Carlow', role_numbers)
insert_into_role_numbers('72370P', 'Borrisokane Community College', 'Borrisokane', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('91508C', 'Boyne Community School', 'Trim', '', '', 'Meath', role_numbers)
insert_into_role_numbers('70380I', 'Breifne College', 'Cootehill Rd.', 'Cavan Town', '', 'Cavan', role_numbers)
insert_into_role_numbers('71610E', 'Bridgetown Vocational College', 'Bridgetown', '', '', 'Wexford', role_numbers)
insert_into_role_numbers('71750U', 'Bush P.P.S.', 'Riverstown', 'Dundalk', '', 'Louth', role_numbers)
insert_into_role_numbers('65270U', 'C.B.S. Carrick On Suir', 'Carrick On Suir', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('60410I', 'C.B.S. James\' St.', 'James\' St.', 'Dublin 8', '', 'Dublin', role_numbers)
insert_into_role_numbers('64930I', 'C.B.S. Mount Sion', 'Barrack St.', 'Waterford City', '', 'Waterford', role_numbers)
insert_into_role_numbers('65080P', 'C.B.S. Roscommon', 'Abbeytown', 'Roscommon Town', '', 'Roscommon', role_numbers)
insert_into_role_numbers('61440W', 'C.B.S. Secondary School', 'The Green', 'Tralee', '', 'Kerry', role_numbers)
insert_into_role_numbers('65450W', 'C.B.S. Thurles', 'O\'Donovan Rossa St.', 'Thurles', '', 'Tipperary', role_numbers)
insert_into_role_numbers('64923L', 'C.B.S. Tramore', 'Tramore', '', '', 'Waterford', role_numbers)
insert_into_role_numbers('60490J', 'C.B.S. Westland Row', 'Westland Row', 'Dublin 2', '', 'Dublin', role_numbers)
insert_into_role_numbers('91310E', 'Cabinteely Community School', 'Cabinteely', 'Dublin 18', '', 'Dublin', role_numbers)
insert_into_role_numbers('63100I', 'Calasanctius College', 'Oranmore', '', '', 'Galway', role_numbers)
insert_into_role_numbers('60732H', 'Caritas College', 'Drumfinn Rd.', 'Ballyfermot', 'Dublin 10', 'Dublin', role_numbers)
insert_into_role_numbers('70420R', 'Carlow Vocational School', 'Kilkenny Rd.', 'Carlow Town', '', 'Carlow', role_numbers)
insert_into_role_numbers('91406R', 'Carndonagh Community School', 'Carndonagh', '', '', 'Donegal', role_numbers)
insert_into_role_numbers('91388S', 'Carrigaline Community School', 'Waterpark', 'Carrigaline', '', 'Cork', role_numbers)
insert_into_role_numbers('71540J', 'Carrigallen Vocational School', 'Carrigallen', '', '', 'Leitrim', role_numbers)
insert_into_role_numbers('91497A', 'Cashel Community School', 'Dualla Rd.', 'Cashel', '', 'Tipperary', role_numbers)
insert_into_role_numbers('72190N', 'Castleblayney College', 'Dublin Rd.', 'Castleblayney', '', 'Monaghan', role_numbers)
insert_into_role_numbers('70520V', 'Castleisland Community College', 'Tonbwee', 'Castleisland', '', 'Kerry', role_numbers)
insert_into_role_numbers('60100Q', 'Castleknock College', 'Castleknock', 'Dublin 15', '', 'Dublin', role_numbers)
insert_into_role_numbers('76062B', 'Castleknock Community College', 'Carpenterstown Rd.', 'Castleknock', 'Dublin 15', 'Dublin', role_numbers)
insert_into_role_numbers('71420W', 'Castlepollard Community College', 'Castlepollard', '', '', 'Westmeath', role_numbers)
insert_into_role_numbers('91493P', 'Castlerea Community School', 'Castlerea', '', '', 'Roscommon', role_numbers)
insert_into_role_numbers('76073G', 'Castletroy College', 'Newtown', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('60540V', 'Catholic University School', '89 Lower Leeson St.', 'Dublin 2', '', 'Dublin', role_numbers)
insert_into_role_numbers('70540E', 'Causeway Comprehensive School', 'Causeway', 'Tralee', '', 'Kerry', role_numbers)
insert_into_role_numbers('72420E', 'Central Technical Institute', 'Clonmel', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('60550B', 'Chanel College', 'Coolock Village', 'Malahide Rd.', 'Dublin 5', 'Dublin', role_numbers)
insert_into_role_numbers('62692I', 'Christ King Girls\' Secondary School', 'Half Moon Lane', 'South Douglas Rd.', '', 'Cork', role_numbers)
insert_into_role_numbers('62520C', 'Christian Brothers College', 'Sidney Hill', 'Wellington Rd.', 'Cork City', 'Cork City', role_numbers)
insert_into_role_numbers('60180R', 'Christian Brothers College', 'Monkstown Park', 'Dun Laoghaire', '', 'Dublin', role_numbers)
insert_into_role_numbers('62420V', 'Christian Brothers Secondary School', 'Mitchelstown', '', '', 'Cork', role_numbers)
insert_into_role_numbers('62360G', 'Christian Brothers Secondary School', 'Castleredmond', 'Midleton', '', 'Cork', role_numbers)
insert_into_role_numbers('63640R', 'Christian Brothers Secondary School', 'Thomas St.', 'Wexford Town', '', 'Wexford', role_numbers)
insert_into_role_numbers('63600F', 'Christian Brothers Secondary School', 'Mountgarrett', 'New Ross', '', 'Wexford', role_numbers)
insert_into_role_numbers('65410K', 'Cistercian College', 'Roscrea', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('70610W', 'City Vocational School', 'New St.', 'Kilkenny Town', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('91412M', 'Clifden Community School', 'Ballyconneely Rd.', 'Clifden', '', 'Galway', role_numbers)
insert_into_role_numbers('70950A', 'Clonakilty Community College', 'Clonakilty', '', '', 'Cork', role_numbers)
insert_into_role_numbers('61720F', 'Clongowes Wood College', 'Clane', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('60092U', 'Clonkeen College', 'Clonkeen Rd.', 'Dun Laoghaire', '', 'Dublin', role_numbers)
insert_into_role_numbers('63730S', 'Cnoc Mhuire', 'Granard', '', '', 'Longford', role_numbers)
insert_into_role_numbers('70960D', 'Coachford College', 'Coachford', '', '', 'Cork', role_numbers)
insert_into_role_numbers('70970G', 'Cobh Community College', 'Carrignafoy', 'Cobh', '', 'Cork', role_numbers)
insert_into_role_numbers('71600B', 'Coláiste Abbain', 'Adamstown', 'Enniscorthy', '', 'Wexford', role_numbers)
insert_into_role_numbers('76081F', 'Coláiste Ailigh', 'Sprackburn House', 'Letterkenny', '', 'Donegal', role_numbers)
insert_into_role_numbers('71650Q', 'Coláiste An Átha', 'Kilmuckridge', 'Gorey', '', 'Wexford', role_numbers)
insert_into_role_numbers('70990M', 'Coláiste An Chraoibhin', 'Duntaheen Road', 'Fermoy', '', 'Cork', role_numbers)
insert_into_role_numbers('71290M', 'Coláiste An Chreagáin', 'Mountbellew', 'Ballinasloe', '', 'Galway', role_numbers)
insert_into_role_numbers('62130M', 'Coláiste An Chroí Naofa', 'Carraig na bhFear', '', '', 'Cork', role_numbers)
insert_into_role_numbers('62301N', 'Colaiste An Phiarsaigh', 'Gleann Maghair', '', '', 'Cork', role_numbers)
insert_into_role_numbers('62580U', 'Coláiste An Spioraid Naoimh', 'Bishopstown', '', '', 'Cork', role_numbers)
insert_into_role_numbers('61320M', 'Coláiste Bhréanainn', 'Killarney', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('70790E', 'Coláiste Bhríde', 'Carnew', '', '', 'Wicklow', role_numbers)
insert_into_role_numbers('63570W', 'Coláiste Bride', 'Enniscorthy', '', '', 'Wexford', role_numbers)
insert_into_role_numbers('60122D', 'Coláiste Bríde', 'New Rd.', 'Clondalkin', 'Dublin 22', 'Dublin', role_numbers)
insert_into_role_numbers('72220T', 'Coláiste Chathail Naofa', 'Youghal Road', '', '', 'Waterford', role_numbers)
insert_into_role_numbers('71840V', 'Colaiste Chiarain', 'Croom', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('76099B', 'Coláiste Chill Mhantáin', 'Burkeen', 'Wicklow Town', '', 'Wicklow', role_numbers)
insert_into_role_numbers('70100W', 'Coláiste Chilliain', 'Bóthar Nangor', 'Cluain Dolcáin', 'Baile Atha Cliath 22', 'Dublin', role_numbers)
insert_into_role_numbers('71470O', 'Coláiste Chluain na Sli', 'Clonaslee', '', '', 'Laois', role_numbers)
insert_into_role_numbers('65610S', 'Colaiste Choilm', 'O\'Moore St.', 'Tullamore', '', 'Offaly', role_numbers)
insert_into_role_numbers('71103K', 'Coláiste Choilm', 'Ballincollig', '', '', 'Cork', role_numbers)
insert_into_role_numbers('60383I', 'Coláiste Choilm', 'Dublin Road', 'Swords', '', 'Dublin', role_numbers)
insert_into_role_numbers('62260C', 'Coláiste Cholmáin', 'Mainistir Fhearmuí', 'Fermoy', '', 'Cork', role_numbers)
insert_into_role_numbers('64610N', 'Coláiste Cholmáin', 'Claremorris', '', '', 'Mayo', role_numbers)
insert_into_role_numbers('71250A', 'Colaiste Cholmcille', 'Indreabhán', 'Spidal', '', 'Galway', role_numbers)
insert_into_role_numbers('91506V', 'Coláiste Cholmcille', 'College St.', 'Ballyshannon', '', 'Donegal', role_numbers)
insert_into_role_numbers('72140V', 'Colaiste Chomain', 'Rossport', '', '', 'Mayo', role_numbers)
insert_into_role_numbers('76076M', 'Colaiste Chraobh Abhann', 'Creowen', 'Kilcoole', '', 'Wicklow', role_numbers)
insert_into_role_numbers('62560O', 'Coláiste Chríost Rí', 'Capwell Road', 'Cork City', '', 'Cork City', role_numbers)
insert_into_role_numbers('63130R', 'Colaiste Chroi Mhuire', 'Spideal', '', '', 'Galway', role_numbers)
insert_into_role_numbers('76065H', 'Coláiste Cois Life', 'Gleann An Ghrífín', '', '', 'Dublin', role_numbers)
insert_into_role_numbers('70620C', 'Coláiste Cois Siúire', 'Mooncoin', '', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('71124S', 'Coláiste Daibhéid', 'Sawmill Street', 'Cork City', '', 'Cork', role_numbers)
insert_into_role_numbers('70021D', 'Coláiste De hÍde', 'Tymon North Rd.', 'Tallaght', 'Dublin. 24', 'Dublin', role_numbers)
insert_into_role_numbers('70330Q', 'Coláiste Dhúlaigh', 'Barryscourt Rd.', 'Coolock', 'Dublin. 17', 'Dublin', role_numbers)
insert_into_role_numbers('76063D', 'Colaiste Dun Iascaigh', 'Cashel Rd.', 'Cahir', '', 'Tipperary', role_numbers)
insert_into_role_numbers('61510R', 'Coláiste Éamann Rís', 'Callan', '', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('60342R', 'Coláiste Eanna', 'Ballyroan', 'Dublin 16', '', 'Dublin', role_numbers)
insert_into_role_numbers('70150O', 'Coláiste Éanna', 'Kilkieran Road', 'Cabra', 'Dublin 7', 'Dublin', role_numbers)
insert_into_role_numbers('62981P', 'Coláiste Einde', 'Threadneedle Road', 'Galway City', '', 'Galway City', role_numbers)
insert_into_role_numbers('70410O', 'Coláiste Eoin', 'Hacketstown', '', '', 'Carlow', role_numbers)
insert_into_role_numbers('70180A', 'Coláiste Eoin', 'Cappagh Road', 'Finglas West', 'Dublin 11', 'Dublin', role_numbers)
insert_into_role_numbers('60041D', 'Coláiste Eoin', 'Baile An Bhóthair', 'Bóthair Stigh Lorgan', '', 'Dublin', role_numbers)
insert_into_role_numbers('71370K', 'Coláiste Ghobnait', 'Inis Oírr', '', 'Cuan Na Gaillimhe', 'Galway', role_numbers)
insert_into_role_numbers('70920O', 'Colaiste Ghobnatan', 'Baile Mhic Ire', '', '', 'Cork', role_numbers)
insert_into_role_numbers('72320A', 'Coláiste Iascaigh', 'Easkey', '', '', 'Sligo', role_numbers)
insert_into_role_numbers('61301I', 'Coláiste Íde', 'Daingean Uí Chúis', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('76093M', 'Coláiste Íde Agus Iosef', 'Abbeyfeale', 'Main Street', '', 'Limerick', role_numbers)
insert_into_role_numbers('76070A', 'Coláiste Ióasef', 'Kilmallock', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('62970K', 'Coláiste Iognáid', 'Br. na Mara', 'Gaillimh', '', 'Galway', role_numbers)
insert_into_role_numbers('60042F', 'Coláiste Íosagáin', 'Bóthar Stigh Lorgan', 'Baile An Bhóthair', '', 'Dublin', role_numbers)
insert_into_role_numbers('68068R', 'Coláiste Íosagáin', 'Portarlington', '', '', 'Laois', role_numbers)
insert_into_role_numbers('70670R', 'Colaiste Lorcain', 'Castledermot', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('64200R', 'Colaiste Mhichil', 'Sexton Street', 'Limerick City', '', 'Limerick City', role_numbers)
insert_into_role_numbers('71700F', 'Colaiste Mhuire', 'Askeaton', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('65140H', 'Colaiste Mhuire', 'Ballymoate', '', '', 'Sligo', role_numbers)
insert_into_role_numbers('63270K', 'Colaiste Mhuire', 'Mullingar', '', '', 'Westmeath', role_numbers)
insert_into_role_numbers('61930Q', 'Coláiste Mhuire', 'College Road', 'Ennis', '', 'Clare', role_numbers)
insert_into_role_numbers('60450U', 'Coláiste Mhuire', 'Bothar Rath Tó', 'Dublin 7', '', 'Dublin', role_numbers)
insert_into_role_numbers('62900M', 'Coláiste Mhuire', 'Ballygar', '', '', 'Galway', role_numbers)
insert_into_role_numbers('70600T', 'Coláiste Mhuire', 'Johnstown', '', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('64691Q', 'Coláiste Mhuire', 'Tuar Mhic Eadaigh', '', '', 'Mayo', role_numbers)
insert_into_role_numbers('72490C', 'Coláiste Mhuire Co-Ed', 'Castlemeadows', 'Thurles', '', 'Tipperary', role_numbers)
insert_into_role_numbers('62200H', 'Colaiste Muire', 'Realt na Mara', 'Crosshaven', '', 'Cork', role_numbers)
insert_into_role_numbers('62180E', 'Coláiste Muire', 'Bishop\'s St', 'Cobh', '', 'Cork', role_numbers)
insert_into_role_numbers('71150T', 'Colaiste na Carraige', 'Carrick', '', '', 'Donegal', role_numbers)
insert_into_role_numbers('71330V', 'Coláiste Na Coiribe', 'Bothar Thuama', 'Galway City', '', 'Galway City', role_numbers)
insert_into_role_numbers('76103M', 'Colaiste na hInse', 'Laytown', '', '', 'Meath', role_numbers)
insert_into_role_numbers('76068N', 'Coláiste na Sceilge', 'Caherciveen', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('76105Q', 'Colaiste Na Sionna', 'Banagher', '', '', 'Offaly', role_numbers)
insert_into_role_numbers('62061T', 'Coláiste na Toirbhirte', 'Árd Aoibhinn', 'Bandon', '', 'Cork', role_numbers)
insert_into_role_numbers('76061W', 'Colaiste Na Trocaire (Mercy Community College)', 'Rathkeale', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('72520I', 'Coláiste Naomh Cormac', 'Kilcormac', '', '', 'Offaly', role_numbers)
insert_into_role_numbers('71320S', 'Coláiste Naomh Feichín', 'Corr na Móna', '', '', 'Galway', role_numbers)
insert_into_role_numbers('61730I', 'Coláiste Naomh Mhuire', 'Sallins Rd.', 'Naas', '', 'Kildare', role_numbers)
insert_into_role_numbers('76091I', 'Coláiste Oiriall', 'Ard Féa', '', '', 'Monaghan', role_numbers)
insert_into_role_numbers('60264A', 'Coláiste Phádraig CBS', 'Roselawn', 'Lucan', '', 'Dublin', role_numbers)
insert_into_role_numbers('76079S', 'Coláiste Phobail Cholmcille', 'Baile Úr, Oileán Thoraí', 'Doirí Beaga', '', 'Donegal', role_numbers)
insert_into_role_numbers('76069P', 'Colaiste Phobáil Ros Cré', 'Corville Rd.', 'Roscrea', '', 'Tipperary', role_numbers)
insert_into_role_numbers('76150V', 'Colaiste Pobail Ac La', 'Achill Sound', 'Westport', '', 'Mayo', role_numbers)
insert_into_role_numbers('76067L', 'Colaiste Pobail Naomh Mhuire', 'Buttevant', '', '', 'Cork', role_numbers)
insert_into_role_numbers('70614k', 'Colaiste Pobail Osraí', 'Bothar Urmhumhan', 'Cill Chainnigh', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('70641K', 'Coláiste Pobail Osraí', 'Bóthar Urmhumhan', '', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('71991T', 'Coláiste Pobail Rath Cairn', 'Ráth Cairn', '', '', 'Meath', role_numbers)
insert_into_role_numbers('76098W', 'Colaiste Pobail Setanta', 'Phibblestown', 'Ongar', 'Dublin 15', 'Dublin', role_numbers)
insert_into_role_numbers('70821M', 'Coláiste Raithín', 'Bóthar Florence', 'Bré', '', 'Wicklow', role_numbers)
insert_into_role_numbers('63880O', 'Colaiste Rís', 'Sraid An Tséipéil', 'Dún Dealgan', '', 'Louth', role_numbers)
insert_into_role_numbers('71000A', 'Colaiste Treasa', 'Kanturk', '', '', 'Cork', role_numbers)
insert_into_role_numbers('70041J', 'Collinstown Park Community College', 'Neilstown Rd.', 'Clondalkin', 'Dublin 22', 'Dublin', role_numbers)
insert_into_role_numbers('71430C', 'Columba College', 'Killucan', '', '', 'Westmeath', role_numbers)
insert_into_role_numbers('72400V', 'Comeragh College', 'Carrick On Suir', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('71960I', 'Community College', 'Dunshaughlin', '', '', 'Meath', role_numbers)
insert_into_role_numbers('70460G', 'Community College', 'Killorglin', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('91360T', 'Community School', 'Castlecomer', '', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('91496V', 'Community School', 'Carrick On Shannon', '', '', 'Leitrim', role_numbers)
insert_into_role_numbers('81006S', 'Comprehensive School', 'Tarbert', 'Listowel', '', 'Kerry', role_numbers)
insert_into_role_numbers('70691C', 'Confey Community College', 'Confey', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('72310U', 'Coola P.P.S.', 'Riverstown', '', '', 'Sligo', role_numbers)
insert_into_role_numbers('91315O', 'Coolmine Community School', 'Clonsilla', 'Dublin 15', '', 'Dublin', role_numbers)
insert_into_role_numbers('72300R', 'Corran College', 'Ballymoate', '', '', 'Sligo', role_numbers)
insert_into_role_numbers('71140Q', 'Crana College', 'Crana Rd.', 'Buncrana', 'Irish Town', 'Donegal', role_numbers)
insert_into_role_numbers('76127D', 'Creagh College', 'Carnew Road', 'Gorey', '', 'Wexford', role_numbers)
insert_into_role_numbers('81014R', 'Crescent College Comprehensive', 'Dooradoyle Rd', 'Dooradoyle', 'Limerick City', 'Limerick City', role_numbers)
insert_into_role_numbers('61690W', 'Cross And Passion College', 'Kilcullen', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('70660O', 'Curragh P.P.S.', 'Mcswiney Road', 'Curragh', '', 'Kildare', role_numbers)
insert_into_role_numbers('60310E', 'Da La Salle College', 'Upper Churchtown Rd.', 'Churchtown', 'Dublin 14', 'Dublin', role_numbers)
insert_into_role_numbers('71020G', 'Davis College', 'Summerhill', 'Mallow', '', 'Cork', role_numbers)
insert_into_role_numbers('76060U', 'Davitt College', 'Springfield', 'Castlebar', '', 'Mayo', role_numbers)
insert_into_role_numbers('63891T', 'De La Salle College', 'Castleblayney Rd.', 'Dundalk', '', 'Louth', role_numbers)
insert_into_role_numbers('62310O', 'De La Salle College', 'Macroom', '', '', 'Cork', role_numbers)
insert_into_role_numbers('64950O', 'De La Salle College', 'Newtown', 'Waterford City', '', 'Waterford City', role_numbers)
insert_into_role_numbers('70040H', 'Deansrath Community College', 'New Nangor Rd.', 'Clondalkin', 'Dublin 22', 'Dublin', role_numbers)
insert_into_role_numbers('71230R', 'Deele College', 'Raphoe', 'Lifford', '', 'Donegal', role_numbers)
insert_into_role_numbers('62540I', 'Deerpark C.B.S.', 'St. Patrick\'s Rd.', 'Cork City', '', 'Cork', role_numbers)
insert_into_role_numbers('71790J', 'Desmond College', 'Station Rd.', 'Newcastle West', '', 'Limerick', role_numbers)
insert_into_role_numbers('60070K', 'Dominican College', 'Sion Hill', 'Cross Ave.', 'Blackrock', 'Dublin', role_numbers)
insert_into_role_numbers('60690R', 'Dominican College', 'Griffith Ave.', 'Drumcondra', 'Dublin 9', 'Dublin', role_numbers)
insert_into_role_numbers('62990Q', 'Dominican College', 'Taylors Hill', 'Galway City', '', 'Galway', role_numbers)
insert_into_role_numbers('61860V', 'Dominican College', 'Wicklow Town', '', '', 'Wicklow', role_numbers)
insert_into_role_numbers('76104O', 'Donabate Community College', 'Portrane Rd.', 'Donabate', '', 'Dublin', role_numbers)
insert_into_role_numbers('91396R', 'Douglas Community School', 'Clermont Ave.', 'Douglas', 'Cork City', 'Cork', role_numbers)
insert_into_role_numbers('60480G', 'Drimnagh Castle Secondary School', 'Long Mile Rd.', 'Walkinstown', 'Dublin 12', 'Dublin', role_numbers)
insert_into_role_numbers('63870l', 'Drogheda Grammar School', 'Mornington Rd.', 'Drogheda', '', 'Louth', role_numbers)
insert_into_role_numbers('70590T', 'Duiske College', 'Graignamanagh', '', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('63920A', 'Dundalk Grammar School', 'The Crescent', 'Dundalk', '', 'Louth', role_numbers)
insert_into_role_numbers('91414Q', 'Dunmore Community School', 'Dunmore', '', '', 'Galway', role_numbers)
insert_into_role_numbers('81016V', 'East Glendalough School', 'Station Rd.', 'Wicklow Town', '', 'Wicklow', role_numbers)
insert_into_role_numbers('72280O', 'Elphin Community College', 'Elphin', 'Castlerea', '', 'Roscommon', role_numbers)
insert_into_role_numbers('70830N', 'Ennis Community College', 'Harmony Row', 'Ennis', '', 'Clare', role_numbers)
insert_into_role_numbers('71630K', 'Enniscorthy Vocational College', 'Milehouse Rd.', 'Enniscorthy', '', 'Wexford', role_numbers)
insert_into_role_numbers('70840Q', 'Ennistymon Vocational School', 'Ennistymon', '', '', 'Clare', role_numbers)
insert_into_role_numbers('71200I', 'Errigal College', 'Windyhall', 'Letterkenny', '', 'Donegal', role_numbers)
insert_into_role_numbers('64410F', 'Eureka Secondary School', 'Kells', '', '', 'Meath', role_numbers)
insert_into_role_numbers('63550Q', 'F.C.J. Secondary School', 'Bunclody', '', '', 'Wexford', role_numbers)
insert_into_role_numbers('70121H', 'Fingal Community College', 'Seatown Rd.', 'Swords', '', 'Dublin', role_numbers)
insert_into_role_numbers('71240U', 'Finn Valley College', 'Drumboe Lower', 'Stranorlar', '', 'Donegal', role_numbers)
insert_into_role_numbers('70140L', 'Firhouse Community College', 'Firhouse Rd.', 'Dublin 24', '', 'Dublin', role_numbers)
insert_into_role_numbers('64420I', 'Franciscan College', 'Gormanstown', '', '', 'Meath', role_numbers)
insert_into_role_numbers('68072I', 'Gael Cholaiste Chill Dara', 'Seanbhóthar Luimnigh', 'Nás na Ríogh', '', 'Kildare', role_numbers)
insert_into_role_numbers('76102K', 'Gaelcholaiste an Eachréidh', 'Coiléar Bán', 'Athenry', '', 'Galway', role_numbers)
insert_into_role_numbers('70440A', 'Gaelcholáiste Cheatharlach', 'Easca', 'Baile an Ceatharlach', '', 'Carlow', role_numbers)
insert_into_role_numbers('70560K', 'Gaelcholáiste Chiarraí', 'Tobar Mhaigh Dor', 'Trá Lí', '', 'Kerry', role_numbers)
insert_into_role_numbers('76107U', 'Gaelcholáiste Chineál Eoghain', 'Muileann Thulaigh Gharbháin', 'Bhun Cranncha', '', 'Donegal', role_numbers)
insert_into_role_numbers('76101I', 'Gaelcholaiste Luimnigh', 'Meal Sior Anraí', 'Limerick City', '', 'Limerick', role_numbers)
insert_into_role_numbers('62531H', 'Gaelcholáiste Mhuire', 'An Mhainistir Thuaidh', 'Cathair Chorcaí', '', 'Cork', role_numbers)
insert_into_role_numbers('76106S', 'Gaelcholáiste na Mara', 'Pairc na bPiarsach', 'Bóthar an Ghleanntáin', 'An tInbhear Mór', 'Wicklow', role_numbers)
insert_into_role_numbers('68078U', 'Gaelcholáiste Phort Lairge', 'Bishop\'s Court', 'Ballygunner', 'Waterford City', 'Waterford', role_numbers)
insert_into_role_numbers('71310P', 'Gairm Scoil Chilleáin Naofa', 'New Inn', 'Ballinasloe', '', 'Galway', role_numbers)
insert_into_role_numbers('71242B', 'Gairmscoil Chú Uladh', 'Béal an Átha Móir', 'An Clochan', 'Leifear', 'Donegal', role_numbers)
insert_into_role_numbers('71300M', 'Gairmscoil Éinne Oileain Arann', 'Cill Rónain', 'Inis Mór', '', 'Galway', role_numbers)
insert_into_role_numbers('71244F', 'Gairmscoil Mhic Diarmada', 'An Leadhbgarbh', 'Arainn Mhór', '', 'Donegal', role_numbers)
insert_into_role_numbers('71270G', 'Gairmscoil Mhuire', 'Athenry', '', '', 'Galway', role_numbers)
insert_into_role_numbers('71380N', 'Gairmscoil na bPiarsach', 'Ros Muc', '', '', 'Galway', role_numbers)
insert_into_role_numbers('91515W', 'Gallen Community School', 'Ferbane', '', '', 'Offaly', role_numbers)
insert_into_role_numbers('71400Q', 'Galway Community College', 'Wellpark', 'Galway City', '', 'Galway', role_numbers)
insert_into_role_numbers('76085N', 'Gealcholáiste Reachrann', 'Bóthar Mhainistir na Gráinsí', 'Domhnach Míde', 'Baile Atha Cliath 13', 'Dublin', role_numbers)
insert_into_role_numbers('76064F', 'Glanmire Community College', 'Glanmire', '', '', 'Cork', role_numbers)
insert_into_role_numbers('91514U', 'Glenamaddy Community School', 'Glenamaddy', '', '', 'Galway', role_numbers)
insert_into_role_numbers('64150F', 'Glenstal Abbey School', 'Murroe', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('60530S', 'Gonzaga College', 'Sandford Rd.', 'Ranelagh', 'Dublin 6', 'Dublin', role_numbers)
insert_into_role_numbers('63610I', 'Good Counsel College', 'New Ross', '', '', 'Wexford', role_numbers)
insert_into_role_numbers('91492N', 'Gorey Community School', 'Esmonde St.', 'Gorey', '', 'Wexford', role_numbers)
insert_into_role_numbers('91498C', 'Gort Community School', 'Gort', '', '', 'Galway', role_numbers)
insert_into_role_numbers('70020B', 'Grange Community College', 'Grange Rd.', 'Donaghmede', 'Dublin 13', 'Dublin', role_numbers)
insert_into_role_numbers('72330D', 'Grange Vocational School', 'Grange', '', '', 'Sligo', role_numbers)
insert_into_role_numbers('70130I', 'Greenhills College', 'Limekiln Ave.', 'Greenhills', 'Dublin 12', 'Dublin', role_numbers)
insert_into_role_numbers('70640I', 'Grennan College', 'Ladywell St.', 'Thomastown', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('91339F', 'Hartstown Community School', 'Hartstown', 'Dublin 15', '', 'Dublin', role_numbers)
insert_into_role_numbers('71850B', 'Hazelwood College', 'Dromcollogher', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('91427C', 'Heywood Community School', 'Ballinakill', '', '', 'Laois', role_numbers)
insert_into_role_numbers('91330K', 'Holy Child Community School', 'Pearse St.', 'Dublin 2', '', 'Dublin', role_numbers)
insert_into_role_numbers('60250M', 'Holy Child Secondary School', 'Military Rd.', 'Killiney', '', 'Dublin', role_numbers)
insert_into_role_numbers('60750J', 'Holy Faith Secondary School', '1 Belgrove Rd.', 'Clontarf', 'Dublin 3', 'Dublin', role_numbers)
insert_into_role_numbers('60791A', 'Holy Faith Secondary School', 'Brookwood Meadow', 'Killester', 'Dublin 5', 'Dublin', role_numbers)
insert_into_role_numbers('91301D', 'Holy Family Community School', 'Kilteel Rd.', 'Rathcoole', '', 'Dublin', role_numbers)
insert_into_role_numbers('61682A', 'Holy Family Secondary School', 'Newbridge', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('63090I', 'Holy Rosary College', 'Mountbellew', '', '', 'Galway', role_numbers)
insert_into_role_numbers('72180K', 'Inver College', 'Carrickmacross', '', '', 'Monaghan', role_numbers)
insert_into_role_numbers('64630T', 'Jesus & Mary Secondary School', 'Gortnor Abbey', 'Crossmolina', '', 'Mayo', role_numbers)
insert_into_role_numbers('65150K', 'Jesus & Mary Secondary School', 'Enniscrone', '', '', 'Sligo', role_numbers)
insert_into_role_numbers('68071G', 'John Scottus Secondary School', '72/76 Morehampton Rd.', 'Donnybrook', 'Dublin 4', 'Dublin', role_numbers)
insert_into_role_numbers('91502N', 'John The Baptist Community School', 'Hospital', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('91530S', 'Kildare Town Community School', 'Dunmurray Rd.', 'Kildare Town', '', 'Kildare', role_numbers)
insert_into_role_numbers('61570M', 'Kilkenny College', 'Castlecomer Rd.', '', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('70450D', 'Killarney Community College', 'New Rd.', 'Kilarney', '', 'Kerry', role_numbers)
insert_into_role_numbers('65630B', 'Killina Presentation Secondary School', 'Rahan', 'Tullamore', '', 'Offaly', role_numbers)
insert_into_role_numbers('91337B', 'Killinarden Community School', 'Killinarden', 'Tallaght', 'Dublin 24', 'Dublin', role_numbers)
insert_into_role_numbers('91448K', 'Kilrush Community School', 'Kilrush', '', '', 'Clare', role_numbers)
insert_into_role_numbers('91499E', 'Kinsale Community School', 'Kinsale', '', '', 'Cork', role_numbers)
insert_into_role_numbers('70240P', 'Kylemore College', 'Kylemore Rd.', 'Ballyfermot', 'Dublin 10', 'Dublin', role_numbers)
insert_into_role_numbers('71720L', 'Lanesboro Community College', 'Lanesboro', '', '', 'Longford', role_numbers)
insert_into_role_numbers('72171J', 'Largy College', 'Analore Rd.', 'Clones', '', 'Monaghan', role_numbers)
insert_into_role_numbers('76077O', 'Larkin Community College', 'Cathal Brugha St.', 'Dublin 1', '', 'Dublin', role_numbers)
insert_into_role_numbers('64270P', 'Laurel Hill Coláiste Fcj', 'Cnoc Na Labhras', 'Limerick City', '', 'Limerick City', role_numbers)
insert_into_role_numbers('64260M', 'Laurel Hill Secondary School FCJ', 'Laurel Hill', 'South Circular Rd.', 'Limerick City', 'Limerick City', role_numbers)
insert_into_role_numbers('91371B', 'Leixlip Community School', 'Celbridge Rd.', 'Leixlip', '', 'Kildare', role_numbers)
insert_into_role_numbers('70500P', 'Listowel Community College', 'Listowel', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('60130C', 'Loreto Abbey Secondary School', 'Dalkey', '', '', 'Dublin', role_numbers)
insert_into_role_numbers('60800V', 'Loreto College', 'Crumlin Rd.', 'Dublin 12', '', 'Dublin', role_numbers)
insert_into_role_numbers('61070P', 'Loreto College', 'Cavan', '', '', 'Cavan', role_numbers)
insert_into_role_numbers('60820E', 'Loreto College', '53 St Stephens Green', 'Dublin 2', '', 'Dublin', role_numbers)
insert_into_role_numbers('60810B', 'Loreto College', 'Swords', '', '', 'Dublin', role_numbers)
insert_into_role_numbers('60240J', 'Loreto College', 'Foxrock', 'Dublin 18', '', 'Dublin', role_numbers)
insert_into_role_numbers('63290Q', 'Loreto College', 'Mullingar', '', '', 'Westmeath', role_numbers)
insert_into_role_numbers('91500J', 'Loreto Community School', 'Convent Rd.', 'Milford', '', 'Donegal', role_numbers)
insert_into_role_numbers('60340N', 'Loreto High School - Beaufort', 'Grange Rd.', 'Rathfarnham', 'Dublin 14', 'Dublin', role_numbers)
insert_into_role_numbers('61580P', 'Loreto Secondary School', 'Granges Rd.', 'Kilkenny', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('64370T', 'Loreto Secondary School', 'St. Michael\'s', 'Navan', '', 'Meath', role_numbers)
insert_into_role_numbers('62840U', 'Loreto Secondary School', 'Letterkenny', '', '', 'Donegal', role_numbers)
insert_into_role_numbers('62270F', 'Loreto Secondary School', 'Fermoy', '', '', 'Cork', role_numbers)
insert_into_role_numbers('60010P', 'Loreto Secondary School', 'Balbriggan', '', '', 'Dublin', role_numbers)
insert_into_role_numbers('65330M', 'Loreto Secondary School', 'Coleville Rd.', 'Clonmel', '', 'Tipperary', role_numbers)
insert_into_role_numbers('63660A', 'Loreto Secondary School', 'Spawell Road', 'Wexford Town', '', 'Wexford', role_numbers)
insert_into_role_numbers('61820J', 'Loreto Secondary School', 'Vevay Rd.', 'Bray', '', 'Wicklow', role_numbers)
insert_into_role_numbers('71560P', 'Lough Allen College', 'Drumkeeran', '', '', 'Leitrim', role_numbers)
insert_into_role_numbers('70080T', 'Lucan Community College', 'Esker Drive', 'Lucan', '', 'Dublin', role_numbers)
insert_into_role_numbers('76130P', 'Luttrellstown Community College', 'Mill Rd.', 'Blancharstown', 'Dublin 15', 'Dublin', role_numbers)
insert_into_role_numbers('76083J', 'Magh Ene College', 'Church Rd.', 'Bundoran', '', 'Donegal', role_numbers)
insert_into_role_numbers('91325R', 'Malahide Community School', 'Broomfield', 'Malahide', '', 'Dublin', role_numbers)
insert_into_role_numbers('71080B', 'Mannix College', 'Charleville', '', '', 'Cork', role_numbers)
insert_into_role_numbers('60300B', 'Manor House School', 'Watermill Rd.', 'Raheny', 'Dublin 5', 'Dublin', role_numbers)
insert_into_role_numbers('70321P', 'Margaret Aylward Community College', 'The Thatch Rd.', 'Whitehall', 'Dublin 9', 'Dublin', role_numbers)
insert_into_role_numbers('76086P', 'Maria Immaculata Community College', 'Dunmanway', '', '', 'Cork', role_numbers)
insert_into_role_numbers('60500J', 'Marian College', 'Ballsbridge', 'Dublin 4', '', 'Dublin', role_numbers)
insert_into_role_numbers('70250S', 'Marino College', '14-20 Marino Mart', 'Fairview', 'Dublin 3', 'Dublin', role_numbers)
insert_into_role_numbers('63190M', 'Marist College', 'Retreat Rd.', 'Athlone', '', 'Westmeath', role_numbers)
insert_into_role_numbers('62000W', 'Mary Immaculate Secondary School', 'Lisdoonvarna', '', '', 'Clare', role_numbers)
insert_into_role_numbers('60840K', 'Maryfield College', 'Glandore Rd.', 'Drumcondra', 'Dublin 9', 'Dublin', role_numbers)
insert_into_role_numbers('60852R', 'Mater Christi', 'Cappagh', 'Finglas', 'Dublin 11', 'Dublin', role_numbers)
insert_into_role_numbers('91400F', 'Mayfield Community School', 'Old Youghal Road', 'Mayfield', '', 'Cork', role_numbers)
insert_into_role_numbers('70700A', 'Maynooth Post Primary School,', 'Moyglare Rd,', 'Maynooth,', '', 'Kildare', role_numbers)
insert_into_role_numbers('71030J', 'McEgan College', 'Macroom', '', '', 'Cork', role_numbers)
insert_into_role_numbers('63221U', 'Meán Scoil An Chlochair', 'Kilbeggan', 'Mullingar', '', 'Westmeath', role_numbers)
insert_into_role_numbers('63010H', 'Meán Scoil Mhuire', 'Newtownsmith', 'Galway City', '', 'Galway City', role_numbers)
insert_into_role_numbers('63760E', 'Meán Scoil Muire', 'Convent Road', 'Longford Town', '', 'Longford', role_numbers)
insert_into_role_numbers('65090S', 'Mean Scoil Muire Gan Smal', 'Convent Of Mercy', 'Roscommon Town', '', 'Roscommon', role_numbers)
insert_into_role_numbers('61260U', 'Mean Scoil Naomh Ioseph', 'Clochar Na Toirbhirte', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('60990G', 'Meanscoil Chroimghlinne', '314/318 Crumlin Road', 'Crumlin', 'Dublin 12', 'Dublin', role_numbers)
insert_into_role_numbers('68080H', 'Meanscoil Gharman', 'Brownswood House', 'Enniscorthy', '', 'Wexford', role_numbers)
insert_into_role_numbers('61710C', 'Meánscoil Iognáid Ris', 'Naas', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('61940T', 'Meánscoil na mBráithre', 'Ennistymon', '', '', 'Clare', role_numbers)
insert_into_role_numbers('61550G', 'Meánscoil na mBráithre Criostaí', 'Sráid Shéamais', 'Baile Chill Chainnigh', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('68075O', 'Meánscoil Nua An Leith Triúigh', 'Castlegregory', 'Tralee', '', 'Kerry', role_numbers)
insert_into_role_numbers('61250R', 'Meanscoil Phadraig Naofa', 'Castleisland', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('76066J', 'Meánscoil San Nioclás', 'Rinn Ó gCuanach', 'Dungarvan', '', 'Waterford', role_numbers)
insert_into_role_numbers('63171I', 'Mercy College', 'Woodford', '', '', 'Galway', role_numbers)
insert_into_role_numbers('65181V', 'Mercy College', 'Chapel Hill', '', '', 'Sligo', role_numbers)
insert_into_role_numbers('60871V', 'Mercy College Coolock', 'St. Brendans Drive', 'Coolock', 'Dublin 5', 'Dublin', role_numbers)
insert_into_role_numbers('62490T', 'Mercy Heights Secondary School', 'Skibereen', '', '', 'Cork', role_numbers)
insert_into_role_numbers('60872A', 'Mercy Secondary School', 'Goldenbridge', 'Inchicore', 'Dublin 8', 'Dublin', role_numbers)
insert_into_role_numbers('68070E', 'Mercy Secondary School', 'Mounthawk', 'Tralee', '', 'Kerry', role_numbers)
insert_into_role_numbers('63710M', 'Mercy Secondary School', 'Ballymahon', '', '', 'Longford', role_numbers)
insert_into_role_numbers('62370J', 'Midleton College', 'Midleton', '', '', 'Cork', role_numbers)
insert_into_role_numbers('91390F', 'Millstreet Community School', 'Millstreet Town', '', '', 'Cork', role_numbers)
insert_into_role_numbers('91501L', 'Moate Community School', 'Church Street', 'Moate', '', 'Westmeath', role_numbers)
insert_into_role_numbers('76089V', 'Mohill Community College', 'Mohill', '', '', 'Leitrim', role_numbers)
insert_into_role_numbers('64830E', 'Monaghan Collegiate School', 'Corlatt', '', '', 'Monaghan', role_numbers)
insert_into_role_numbers('60140F', 'Mount Anville Secondary School', 'Mount Anville Rd.', 'Goatstown', 'Dublin 14', 'Dublin', role_numbers)
insert_into_role_numbers('60853T', 'Mount Carmel Secondary School', 'Kings Inn St.', 'Dublin 1', '', 'Dublin', role_numbers)
insert_into_role_numbers('62661U', 'Mount Mercy College', 'Model Farm Rd.', 'Cork City', '', 'Cork', role_numbers)
insert_into_role_numbers('60120W', 'Mount Sackville Secondary School', 'Chapelizod', 'Dublin 20', '', 'Dublin', role_numbers)
insert_into_role_numbers('70141N', 'Mount Seskin Community College', 'Jobstown', 'Tallaght', 'Dublin 24', 'Dublin', role_numbers)
insert_into_role_numbers('64620Q', 'Mount St. Michael', 'Convent Of Mercy', 'Claremorris', '', 'Mayo', role_numbers)
insert_into_role_numbers('62470N', 'Mount St. Michael', 'Rosscarbery', '', '', 'Cork', role_numbers)
insert_into_role_numbers('81002K', 'Mount Temple Comprehensive School', 'Malahide Rd.', '', '', 'Dublin', role_numbers)
insert_into_role_numbers('91426A', 'Mountmellick Community School', 'Mountmellick', '', '', 'Laois', role_numbers)
insert_into_role_numbers('91550B', 'Mountrath Community School', 'Dysartbeigh', 'Mountrath', '', 'Laois', role_numbers)
insert_into_role_numbers('76084L', 'Moville Community College', 'Carrownaff', 'Moville', '', 'Donegal', role_numbers)
insert_into_role_numbers('60121B', 'Moyle Park College', 'Clondalkin', 'Dublin 22', '', 'Dublin', role_numbers)
insert_into_role_numbers('72020L', 'Moyne College', 'Ballina', '', '', 'Mayo', role_numbers)
insert_into_role_numbers('91436D', 'Moyne Community School', 'Moyne', '', '', 'Longford', role_numbers)
insert_into_role_numbers('60710U', 'Muckross Park College', 'Donnybrook', 'Dublin 4', '', 'Dublin', role_numbers)
insert_into_role_numbers('71450I', 'Mullingar Community College', 'Millmount Rd.', 'Mullingar', '', 'Westmeath', role_numbers)
insert_into_role_numbers('71220O', 'Mulroy College', 'Milford', 'Letterkenny', '', 'Donegal', role_numbers)
insert_into_role_numbers('71110H', 'Nagle Community College', 'Mahon', 'Blackrock', '', 'Cork', role_numbers)
insert_into_role_numbers('62210K', 'Nagle Rice Secondary School', 'Doneraile', '', '', 'Cork', role_numbers)
insert_into_role_numbers('72440K', 'Nenagh Vocational School', 'Dromin Rd.', 'Nenagh', '', 'Tipperary', role_numbers)
insert_into_role_numbers('71660T', 'New Ross Vocational College', 'New Ross', '', '', 'Wexford', role_numbers)
insert_into_role_numbers('61680T', 'Newbridge College', 'Newbridge', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('81001I', 'Newpark Comprehensive School', 'Newtown Park Avenue', 'Blackrock', '', 'Dublin', role_numbers)
insert_into_role_numbers('65010R', 'Newtown School', 'Newtown Rd.', '', '', 'Waterford', role_numbers)
insert_into_role_numbers('62530F', 'North Monastery Secondary School', 'Our Lady\'s Mount', 'North Monastery Rd.', '', 'Cork', role_numbers)
insert_into_role_numbers('62621I', 'North Presentation Secondary School', 'Farranree', 'Cork City', '', 'Cork', role_numbers)
insert_into_role_numbers('60160L', 'Notre Dame Secondary School', 'Upper Churchtown Rd.', 'Dublin 14', '', 'Dublin', role_numbers)
insert_into_role_numbers('71770D', 'Ó Fiaich College', 'Dublin Rd.', 'Dundalk', '', 'Louth', role_numbers)
insert_into_role_numbers('72540O', 'Oaklands Community College', 'Sr. Senan Avenue', 'Edenderry', '', 'Offaly', role_numbers)
insert_into_role_numbers('60050E', 'Oatlands College', 'Mount Merrion', 'Blackrock', '', 'Dublin', role_numbers)
insert_into_role_numbers('71980O', 'O\'Carolan College', 'Nobber', '', '', 'Meath', role_numbers)
insert_into_role_numbers('60440R', 'O\'Connell School', 'North Richmond St.', 'Dublin 1', '', 'Dublin', role_numbers)
insert_into_role_numbers('91336W', 'Old Bawn Community School', 'Old Bawn', 'Tallaght', 'Dublin 24', 'Dublin', role_numbers)
insert_into_role_numbers('64971W', 'Our Lady Of  Mercy Secondary School', 'Ozanam St.', 'Waterford City', '', 'Waterford City', role_numbers)
insert_into_role_numbers('63630O', 'Our Lady Of Lourdes Secondary School', 'Rosbercon', 'New Ross', '', 'Wexford', role_numbers)
insert_into_role_numbers('60870T', 'Our Lady Of Mercy College', 'Beaumont', 'Dublin 9', '', 'Dublin', role_numbers)
insert_into_role_numbers('60991I', 'Our Lady Of Mercy Secondary School', 'Mourne Rd.', 'Drimnagh', 'Dublin 12', 'Dublin', role_numbers)
insert_into_role_numbers('63210P', 'Our Lady\'s Bower', 'Retreat Rd.', 'Athlone', '', 'Westmeath', role_numbers)
insert_into_role_numbers('63850F', 'Our Ladys College', 'Greenhills', 'Drogheda', '', 'Louth', role_numbers)
insert_into_role_numbers('60891E', 'Our Lady\'s Grove Secondary School', 'Goatstown Rd.', 'Dublin 14', '', 'Dublin', role_numbers)
insert_into_role_numbers('60860Q', 'Our Ladys School', 'Templeogue Rd.', 'Terenure', 'Dublin 6W', 'Dublin', role_numbers)
insert_into_role_numbers('65440T', 'Our Ladys Secondary School', 'Templemore', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('64570E', 'Our Lady\'s Secondary School', 'Belmullet', '', '', 'Mayo', role_numbers)
insert_into_role_numbers('64770M', 'Our Lady\'s Secondary School', 'Castleblayney', '', '', 'Monaghan', role_numbers)
insert_into_role_numbers('62330U', 'Patrician Academy', 'Mallow', '', '', 'Cork', role_numbers)
insert_into_role_numbers('60571J', 'Patrician College', 'Deanstown Ave.', 'Finglas West', 'Dublin 11', 'Dublin', role_numbers)
insert_into_role_numbers('64750G', 'Patrician High School', 'Carrickmacross', '', '', 'Monaghan', role_numbers)
insert_into_role_numbers('65350S', 'Patrician Presentation', 'Rocklow Rd.', 'Fethard', '', 'Tipperary', role_numbers)
insert_into_role_numbers('61681V', 'Patrician Secondary School', 'Newbridge', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('70300H', 'Pearse College - Colaiste An Phiarsaigh', 'Clogher Rd.', 'Crumlin', 'Dublin 12', 'Dublin', role_numbers)
insert_into_role_numbers('91302F', 'Phobailscoil Iosolde', 'Palmerstown', 'Dublin 20', '', 'Dublin', role_numbers)
insert_into_role_numbers('70710D', 'Piper\'s Hill College', 'Killashee', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('70310K', 'Plunket College', 'Swords Rd.', 'Whitehall', 'Dublin 9', 'Dublin', role_numbers)
insert_into_role_numbers('91408V', 'Pobalscoil Chloich Cheannfhaola', 'An Fálcarrach', '', '', 'Donegal', role_numbers)
insert_into_role_numbers('91511O', 'Pobalscoil Chorca Dhuibhne', 'Bóthar An Spá', 'An Daingean', '', 'Kerry', role_numbers)
insert_into_role_numbers('91409A', 'Pobalscoil Ghaoth Dobhair', 'Doirí Beaga', 'Tir Chonaill', '', 'Donegal', role_numbers)
insert_into_role_numbers('91503P', 'Pobalscoil Inbhear Sceine', 'Kenmare', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('91513S', 'Pobalscoil Na Tríonóide', 'Youghal', '', '', 'Cork', role_numbers)
insert_into_role_numbers('91342R', 'Pobalscoil Neasáin', 'Baldoyle', 'Dublin 13', '', 'Dublin', role_numbers)
insert_into_role_numbers('71510A', 'Portlaoise College', 'Mountrath Road', '', '', 'Laois', role_numbers)
insert_into_role_numbers('91324P', 'Portmarnock Community School', 'Carrickhill Rd.', 'Portmarnock', '', 'Dublin', role_numbers)
insert_into_role_numbers('91413O', 'Portumna Community School', 'St. Brigid\'s Rd.', 'Portumna', '', 'Galway', role_numbers)
insert_into_role_numbers('61150N', 'Presentation / De La Salle College', 'Royal Oak Rd.', 'Carlow Town', '', 'Carlow', role_numbers)
insert_into_role_numbers('62570R', 'Presentation Brothers College', 'Mardyke', 'Cork City', '', 'Cork City', role_numbers)
insert_into_role_numbers('61141M', 'Presentation College', 'Askea', 'Carlow town', '', 'Carlow', role_numbers)
insert_into_role_numbers('76092K', 'Presentation College', 'Terenure', 'Dublin 6W', '', 'Dublin', role_numbers)
insert_into_role_numbers('63040Q', 'Presentation College', 'Headford', '', '', 'Galway', role_numbers)
insert_into_role_numbers('62870G', 'Presentation College', 'Athenry', '', '', 'Galway', role_numbers)
insert_into_role_numbers('63170G', 'Presentation College', 'Currylea', 'Tuam', '', 'Galway', role_numbers)
insert_into_role_numbers('61800D', 'Presentation College', 'Putland Rd.', 'Bray', '', 'Wicklow', role_numbers)
insert_into_role_numbers('61380H', 'Presentation Secondary School', 'Listowel', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('60792C', 'Presentation Secondary School', 'Warrenmount', 'Dublin 8', '', 'Dublin', role_numbers)
insert_into_role_numbers('62693K', 'Presentation Secondary School', 'Ballyphehane', 'Cork City', '', 'Cork', role_numbers)
insert_into_role_numbers('62421A', 'Presentation Secondary School', 'Mitchelstown', 'Mallow', '', 'Cork', role_numbers)
insert_into_role_numbers('63000E', 'Presentation Secondary School', 'Presentation Rd', 'Galway City', '', 'Galway City', role_numbers)
insert_into_role_numbers('61410N', 'Presentation Secondary School', 'Miltown', 'Killarney', '', 'Kerry', role_numbers)
insert_into_role_numbers('61450C', 'Presentation Secondary School', 'Tralee', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('61590S', 'Presentation Secondary School', 'Loughboy', '', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('64250J', 'Presentation Secondary School', 'Sexton Street', 'Limerick City', '', 'Limerick', role_numbers)
insert_into_role_numbers('65460C', 'Presentation Secondary School', 'Thurles', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('65240L', 'Presentation Secondary School', 'Ballingarry', 'Thurles', '', 'Tipperary', role_numbers)
insert_into_role_numbers('65340P', 'Presentation Secondary School', 'Clonmel', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('64970U', 'Presentation Secondary School', 'Waterford City', '', '', 'Waterford', role_numbers)
insert_into_role_numbers('63661C', 'Presentation Secondary School', 'Grogan\'s Rd.', 'Summerhill', 'Wexford Town', 'Wexford', role_numbers)
insert_into_role_numbers('91431Q', 'Ramsgrange Community School', 'Ramsgrange', 'New Ross', '', 'Wexford', role_numbers)
insert_into_role_numbers('60090Q', 'Rathdown School', 'Upper Glenageary Rd.', 'Glenageary', '', 'Dublin', role_numbers)
insert_into_role_numbers('76088T', 'Ratoath College', 'Jamestown', 'Ratoath', '', 'Meath', role_numbers)
insert_into_role_numbers('62691G', 'Regina Mundi College', 'Douglas Rd.', '', '', 'Cork', role_numbers)
insert_into_role_numbers('61910K', 'Rice College', 'New Rd.', 'Ennis', '', 'Clare', role_numbers)
insert_into_role_numbers('64700O', 'Rice College', 'Castlebar Road', 'Wesport', '', 'Mayo', role_numbers)
insert_into_role_numbers('70200D', 'Ringsend College', 'Cambridge Rd.', 'Ringsend', 'Dublin 4', 'Dublin', role_numbers)
insert_into_role_numbers('70081V', 'Riversdale Community College', 'Blanchardstown Rd North', 'Dublin 15', '', 'Dublin', role_numbers)
insert_into_role_numbers('62460K', 'Rochestown College', 'Rochestown', '', '', 'Cork', role_numbers)
insert_into_role_numbers('60321J', 'Rockbrook Park School', 'Edmondstown Road', 'Rathfarnham', 'Dublin 16', 'Dublin', role_numbers)
insert_into_role_numbers('60081P', 'Rockford Manor Secondary School', 'Stradbrook Rd.', 'Blackrock', '', 'Dublin', role_numbers)
insert_into_role_numbers('65300D', 'Rockwell College', 'Cashel', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('60841M', 'Rosary College', 'Armagh Rd.', 'Crumlin', 'Dublin 12', 'Dublin', role_numbers)
insert_into_role_numbers('72290R', 'Roscommon Community School', 'Lisnamult', '', '', 'Roscommon', role_numbers)
insert_into_role_numbers('60930L', 'Rosemont School', 'Enniskerry Road', 'Sandyford', 'D.18', 'Dublin', role_numbers)
insert_into_role_numbers('91344V', 'Rosmini Community School', 'Grace Park Rd.', 'Drumcondra', 'Dublin 9', 'Dublin', role_numbers)
insert_into_role_numbers('71090E', 'Rossa College', 'Skibbereen', '', '', 'Cork', role_numbers)
insert_into_role_numbers('91407T', 'Rosses Community School', 'Dungloe', '', '', 'Donegal', role_numbers)
insert_into_role_numbers('61080S', 'Royal School Cavan', 'College Street', 'Cavan', '', 'Cavan', role_numbers)
insert_into_role_numbers('64710R', 'Sacred Heart School', 'Castelbar Rd.', 'Westport', '', 'Mayo', role_numbers)
insert_into_role_numbers('62170B', 'Sacred Heart Secondary School', 'Clonakilty', '', '', 'Cork', role_numbers)
insert_into_role_numbers('63860I', 'Sacred Heart Secondary School', 'Sunnyside', '', '', 'Louth', role_numbers)
insert_into_role_numbers('65620V', 'Sacred Heart Secondary School', 'Daingean Rd.', 'Tullamore', '', 'Offaly', role_numbers)
insert_into_role_numbers('60720A', 'Saint Dominic\'s Secondary School', 'Kylemore Rd.', 'Ballyfermot', 'Dublin 10', 'Dublin', role_numbers)
insert_into_role_numbers('63001G', 'Salerno Secondary School', 'Threadneedle Rd.', 'Salthill', '', 'Galway', role_numbers)
insert_into_role_numbers('61661P', 'Salesian College', 'Celbridge', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('64180O', 'Salesian Secondary College', 'Pallaskenry', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('64280S', 'Salesian Secondary School', 'Fernbank', 'North Circular Road', 'Limerick City', 'Limerick City', role_numbers)
insert_into_role_numbers('60341P', 'Sancta Maria College', 'Ballyroan', 'Rathfarnham', 'Dublin 16', 'Dublin', role_numbers)
insert_into_role_numbers('64660F', 'Sancta Maria College', 'Louisburgh', '', '', 'Mayo', role_numbers)
insert_into_role_numbers('60640C', 'Sandford Park School Ltd', 'Sandford Rd.', 'Ranelagh', 'Dublin 6', 'Dublin', role_numbers)
insert_into_role_numbers('60380C', 'Santa Sabina Dominican College', 'Greenfield Rd.', 'Sutton', 'Dublin 13', 'Dublin', role_numbers)
insert_into_role_numbers('70900I', 'Scariff Community College', 'Scariff', '', '', 'Clare', role_numbers)
insert_into_role_numbers('71102I', 'Schull Community College', 'Colla Rd.', 'Schull', '', 'Cork', role_numbers)
insert_into_role_numbers('70570N', 'Scoil Aireagail', 'Ballyhale', '', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('64300V', 'Scoil Carmel', 'O\'Connell Ave.', 'Limerick City', '', 'Limerick', role_numbers)
insert_into_role_numbers('60700R', 'Scoil Chaitriona', 'Bóthar Mobhí', 'Glasnaíon', 'Ath Cliath 9', 'Dublin', role_numbers)
insert_into_role_numbers('70750P', 'Scoil Chonglais', 'Baltinglass', '', '', 'Wicklow', role_numbers)
insert_into_role_numbers('63451O', 'Scoil Chríost Rí', 'Presentation Secondary School', 'Borris Rd.', '', 'Laois', role_numbers)
insert_into_role_numbers('81012N', 'Scoil Chuimsitheach Chiaráin', 'An Cheathrú Rua', '', '', 'Galway', role_numbers)
insert_into_role_numbers('61691B', 'Scoil Dara', 'Church St.', 'Kilcock', '', 'Kildare', role_numbers)
insert_into_role_numbers('61950W', 'Scoil Mhuire', 'Ennistymon', '', '', 'Clare', role_numbers)
insert_into_role_numbers('62690E', 'Scoil Mhuire', '2 Sidney Place', 'Wellington Rd.', 'Cork City', 'Cork City', role_numbers)
insert_into_role_numbers('62290L', 'Scoil Mhuire', 'Kanturk', '', '', 'Cork', role_numbers)
insert_into_role_numbers('70931T', 'Scoil Mhuire', 'Béal Atha an Ghaorthaidh', '', '', 'Cork', role_numbers)
insert_into_role_numbers('64450R', 'Scoil Mhuire', 'Convent of Mercy', 'Kells', '', 'Meath', role_numbers)
insert_into_role_numbers('65100S', 'Scoil Mhuire', 'Strokestown', '', '', 'Roscommon', role_numbers)
insert_into_role_numbers('65280A', 'Scoil Mhuire', 'Greenhill', 'Carrick on Suir', '', 'Tipperary', role_numbers)
insert_into_role_numbers('64170L', 'Scoil Mhuire agus Íde', 'Bóthar Buí', 'Newcastle West', '', 'Limerick', role_numbers)
insert_into_role_numbers('91372D', 'Scoil Mhuire Community School', 'Clane', 'Naas', '', 'Kildare', role_numbers)
insert_into_role_numbers('62090D', 'Scoil Mhuire Gan Smal', 'Shean Lower', 'Blarney', '', 'Cork', role_numbers)
insert_into_role_numbers('62770C', 'Scoil Mhuire Secondary School', 'St. Oran\'s Rd.', 'Buncrana', '', 'Donegal', role_numbers)
insert_into_role_numbers('64690O', 'Scoil Muire agus Padraig', 'Swinford', '', '', 'Mayo', role_numbers)
insert_into_role_numbers('64880T', 'Scoil na mBraithre', 'Dungarvan', '', '', 'Waterford', role_numbers)
insert_into_role_numbers('62440E', 'Scoil na mBráithre Chríostaí', 'Bakers Rd.', 'Charleville', '', 'Cork', role_numbers)
insert_into_role_numbers('91411K', 'Scoil Phobail Mhic Dara', 'Carna', '', '', 'Galway', role_numbers)
insert_into_role_numbers('91504R', 'Scoil Phobail Sliabh Luachra', 'Rathmore', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('64130W', 'Scoil Pól', 'Kilfinane', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('72430H', 'Scoil Ruain', 'Killenaule', 'Thurles', '', 'Tipperary', role_numbers)
insert_into_role_numbers('71780G', 'Scoil Uí Mhuiri', 'Barn Rd.', 'Dunleer', '', 'Louth', role_numbers)
insert_into_role_numbers('63050T', 'Seamount College', 'Kinvara', '', '', 'Galway', role_numbers)
insert_into_role_numbers('81007U', 'Shannon Comprehensive School', 'Shannon', '', '', 'Clare', role_numbers)
insert_into_role_numbers('76078Q', 'Skerries Community College', 'Skerries', '', '', 'Dublin', role_numbers)
insert_into_role_numbers('65190W', 'Sligo Grammar School', 'The Mall', 'Sligo Town', '', 'Sligo', role_numbers)
insert_into_role_numbers('62880J', 'St Josephs College', 'Gearrbhaile', 'Béal Átha na Sluaighe', '', 'Galway', role_numbers)
insert_into_role_numbers('71280J', 'St.  Brigid\'s Vocational School', 'Loughrea', '', '', 'Galway', role_numbers)
insert_into_role_numbers('60481I', 'St. Aidan\'s Christian Brothers School', 'Collins Avenue Ext', 'Whitehall', 'Dublin 9', 'Dublin', role_numbers)
insert_into_role_numbers('71101G', 'St. Aidan\'s Community College', 'Ballincolly', 'Dublin Hill', 'Cork City', 'Cork City', role_numbers)
insert_into_role_numbers('91338D', 'St. Aidan\'s Community School', 'Brookfield', 'Tallaght', 'Dublin 24', 'Dublin', role_numbers)
insert_into_role_numbers('81005Q', 'St. Aidan\'s Comprehensive School', 'Cootehill', '', '', 'Cavan', role_numbers)
insert_into_role_numbers('72480W', 'St. Ailbe\'s School', 'Rosanna Road', 'Tipperary Town', '', 'Tipperary', role_numbers)
insert_into_role_numbers('62140P', 'St. Aloysius College', 'Carrigtwohill', '', '', 'Cork', role_numbers)
insert_into_role_numbers('63191O', 'St. Aloysius College', 'The Park', 'Athlone', '', 'Westmeath', role_numbers)
insert_into_role_numbers('62630J', 'St. Aloysius School', 'St. Maries of the Isle', 'Sharman Crawford St.', 'Cork City', 'Cork City', role_numbers)
insert_into_role_numbers('60650F', 'St. Andrew\'s College', 'Booterstown Ave.', 'Blackrock', '', 'Dublin', role_numbers)
insert_into_role_numbers('64990D', 'St. Angela\'s', 'Ursuline Convent', 'Waterford City', '', 'Waterford', role_numbers)
insert_into_role_numbers('62640M', 'St. Angela\'s College', 'St. Patrick\'s Hill', 'Cork City', '', 'Cork', role_numbers)
insert_into_role_numbers('70901K', 'St. Anne\'s Community College', 'Killaloe', '', '', 'Clare', role_numbers)
insert_into_role_numbers('65500L', 'St. Anne\'s Secondary School', 'Rosanna Rd.', 'Tipperary Town', '', 'Tipperary', role_numbers)
insert_into_role_numbers('91512Q', 'St. Attracta\'s Community School', 'Ballyara', 'Tubbercurry', '', 'Sligo', role_numbers)
insert_into_role_numbers('64890W', 'St. Augustine\'s College', 'Abbeyside', 'Dungarvan', '', 'Waterford', role_numbers)
insert_into_role_numbers('60261R', 'St. Benildus College', 'Upper Kilmacud Rd.', 'Stillorgan', '', 'Dublin', role_numbers)
insert_into_role_numbers('61790D', 'St. Brendan\'s College', 'Woodbrook', 'Bray', '', 'Wicklow', role_numbers)
insert_into_role_numbers('72050U', 'St. Brendan\'s College', 'Belmullet', '', '', 'Mayo', role_numbers)
insert_into_role_numbers('91491L', 'St. Brendan\'s Community School', 'Birr', '', '', 'Offaly', role_numbers)
insert_into_role_numbers('70350W', 'St. Bricin\'s Vocational School', 'Belturbet', '', '', 'Cavan', role_numbers)
insert_into_role_numbers('61520U', 'St. Brigid\'s College', 'Callan', '', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('63160D', 'St. Brigid\'s School', 'Convent Of Mercy', 'Tuam', '', 'Galway', role_numbers)
insert_into_role_numbers('61340S', 'St. Brigid\'s Secondary School', 'New Street', 'Killarney', '', 'Kerry', role_numbers)
insert_into_role_numbers('70910L', 'St. Brogan\'s College', 'Bandon', 'Kilbrogan', '', 'Cork', role_numbers)
insert_into_role_numbers('91447I', 'St. Caimin\'s Community School', 'Tullyvarraga', 'Shannon', '', 'Clare', role_numbers)
insert_into_role_numbers('71241W', 'St. Catherine\'s Vocational School', 'Donegal Road', 'Killybegs', '', 'Donegal', role_numbers)
insert_into_role_numbers('91456J', 'St. Ciaran\'s Community School', 'Navan Rd.', 'Kells', '', 'Meath', role_numbers)
insert_into_role_numbers('61051L', 'St. Clare\'s College', 'Virginia Rd.', 'Ballyjamesduff', '', 'Cavan', role_numbers)
insert_into_role_numbers('81013P', 'St. Clare\'s Comprehensive School', 'Manorhamilton', '', '', 'Leitrim', role_numbers)
insert_into_role_numbers('64220A', 'St. Clement\'s College', 'South Circular Rd.', 'Limerick City', '', 'Limerick City', role_numbers)
insert_into_role_numbers('71050P', 'St. Colman\'s Community College', 'Youghal Rd.', 'Midleton', '', 'Cork', role_numbers)
insert_into_role_numbers('91510M', 'St. Colmcille\'s Community School', 'Scholarstown Rd', 'Knocklyon', 'Dublin 16', 'Dublin', role_numbers)
insert_into_role_numbers('60320H', 'St. Columba\'s College', 'Whitechurch', 'Dublin 14', '', 'Dublin', role_numbers)
insert_into_role_numbers('62861F', 'St. Columba\'s College', 'Stranorlar', 'Lifford', '', 'Donegal', role_numbers)
insert_into_role_numbers('81010J', 'St. Columba\'s Comprehensive School', 'Glenties', '', '', 'Donegal', role_numbers)
insert_into_role_numbers('60590N', 'St. Conleth\'s College', '28 Clyde Rd.', 'Ballsbridge', 'Dublin 4', 'Dublin', role_numbers)
insert_into_role_numbers('70680U', 'St. Conleth\'s Community College', 'Station Rd.', 'Newbridge', '', 'Kildare', role_numbers)
insert_into_role_numbers('62930V', 'St. Cuan\'s College', 'Castleblakney', 'Ballinasloe', '', 'Galway', role_numbers)
insert_into_role_numbers('60471F', 'St. David\'s Christian Brothers School', 'Malahide Road', 'Artane', 'Dublin 5', 'Dublin', role_numbers)
insert_into_role_numbers('61830M', 'St. David\'s Holy Faith Secondary', 'Co-Educational School', 'Greystones', '', 'Wicklow', role_numbers)
insert_into_role_numbers('60491L', 'St. Declan\'s College', 'Nephin Rd.', 'Cabra', 'Dublin 7', 'Dublin', role_numbers)
insert_into_role_numbers('72230W', 'St. Declan\'s Community College', 'Kilmacthomas', '', '', 'Waterford', role_numbers)
insert_into_role_numbers('60731F', 'St. Dominic\'s College', 'Cabra', 'Dublin 7', '', 'Dublin', role_numbers)
insert_into_role_numbers('91446G', 'St. Enda\'s Community School', 'Kilmallock Rd.', 'Limerick City', '', 'Limerick', role_numbers)
insert_into_role_numbers('62830R', 'St. Eunan\'s College', 'Letterkenny', '', '', 'Donegal', role_numbers)
insert_into_role_numbers('62480Q', 'St. Fachtna\'s - De La Salle College', 'Skibbereen', '', '', 'Cork', role_numbers)
insert_into_role_numbers('71040M', 'St. Fanahan\'s College', 'Mitchelstown', '', '', 'Cork', role_numbers)
insert_into_role_numbers('70720G', 'St. Farnan\'s Post Primary School', 'Prosperous', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('71520D', 'St. Fergal\'s College', 'Rathdowney', '', '', 'Laois', role_numbers)
insert_into_role_numbers('63280N', 'St. Finian\'s College', 'Mullingar', '', '', 'Westmeath', role_numbers)
insert_into_role_numbers('70120F', 'St. Finian\'s Community College', 'Castlefarm', 'Swords', '', 'Dublin', role_numbers)
insert_into_role_numbers('64040V', 'St. Fintan\'s C.B.S.', 'Doon', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('60370W', 'St. Fintan\'s High School', 'Dublin Road', 'Sutton', 'Dublin 13', 'Dublin', role_numbers)
insert_into_role_numbers('71970L', 'St. Fintinas Post Primary School', 'Longwood', 'Enfield', '', 'Meath', role_numbers)
insert_into_role_numbers('61920N', 'St. Flannan\'s College', 'Ennis', '', '', 'Clare', role_numbers)
insert_into_role_numbers('64580H', 'St. Geralds College', 'Newport Road', 'Castlebar', '', 'Mayo', role_numbers)
insert_into_role_numbers('61811I', 'St. Gerard\'s School', 'Thornhill Rd.', 'Bray', '', 'Wicklow', role_numbers)
insert_into_role_numbers('68074M', 'St. Jarlaths College', 'Tuam', '', '', 'Galway', role_numbers)
insert_into_role_numbers('76075K', 'St. John Bosco Community College', 'Kildysart', '', '', 'Clare', role_numbers)
insert_into_role_numbers('60510M', 'St. John\'s College De La Salle', 'Le Fanu Rd.', 'Ballyfermot', 'Dublin 10', 'Dublin', role_numbers)
insert_into_role_numbers('60260P', 'St. Joseph of Cluny', 'Bellevue Park', 'Ballinclea Rd.', 'Killiney', 'Dublin', role_numbers)
insert_into_role_numbers('64590K', 'St. Joseph\'s', 'Clochar Na Trócaire', 'Castlebar', '', 'Mayo', role_numbers)
insert_into_role_numbers('60390F', 'St. Joseph\'s C.B.S.', 'Merville Ave.', 'Fairview', 'Dublin 3', 'Dublin', role_numbers)
insert_into_role_numbers('63840C', 'St. Joseph\'s CBS', 'Newfoundwell', 'Drogheda', '', 'Louth', role_numbers)
insert_into_role_numbers('65370B', 'St. Joseph\'s Christian Brothers School', 'Summerhill', 'Nenagh', '', 'Tipperary', role_numbers)
insert_into_role_numbers('60263V', 'St. Joseph\'s College', 'Girls\' Secondary School', 'Lucan', '', 'Dublin', role_numbers)
insert_into_role_numbers('65241N', 'St. Joseph\'s College', 'Borrisoleigh', 'Thurles', '', 'Tipperary', role_numbers)
insert_into_role_numbers('62960H', 'St. Joseph\'s College', 'Nun\'s Island', 'Galway City', '', 'Galway City', role_numbers)
insert_into_role_numbers('72450N', 'St. Joseph\'s College', 'Borrisoleigh', 'Thurles', '', 'Tipperary', role_numbers)
insert_into_role_numbers('63211R', 'St. Joseph\'s College', 'Summerhill', 'Athlone', '', 'Westmeath', role_numbers)
insert_into_role_numbers('70880F', 'St. Joseph\'s Community College', 'Carrigholt Rd.', 'Kilkee', '', 'Clare', role_numbers)
insert_into_role_numbers('60843Q', 'St. Joseph\'s Secondary School', 'Stanhope St.', 'Dublin 7', '', 'Dublin', role_numbers)
insert_into_role_numbers('64600K', 'St. Joseph\'s Secondary School', 'Charlestown', 'Claremorris', '', 'Mayo', role_numbers)
insert_into_role_numbers('60343T', 'St. Joseph\'s Secondary School', 'Convent Lane', 'Rush', '', 'Dublin', role_numbers)
insert_into_role_numbers('64050B', 'St. Joseph\'s Secondary School', 'Doon', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('64640W', 'St. Joseph\'s Secondary School', 'Foxford', '', '', 'Mayo', role_numbers)
insert_into_role_numbers('63310T', 'St. Joseph\'s Secondary School', 'Rochfortbridge', 'Mullingar', '', 'Westmeath', role_numbers)
insert_into_role_numbers('62010C', 'St. Joseph\'s Secondary School', 'Spanish Point', 'Milltown Malbay', '', 'Clare', role_numbers)
insert_into_role_numbers('62020F', 'St. Joseph\'s Secondary School', 'Tulla', '', '', 'Clare', role_numbers)
insert_into_role_numbers('61220I', 'St. Joseph\'s Secondary School', 'Doon Road', 'Ballybunion', '', 'Kerry', role_numbers)
insert_into_role_numbers('64360Q', 'St. Joseph\'s Secondary School', 'Mercy Convent', 'Navan', '', 'Meath', role_numbers)
insert_into_role_numbers('60581M', 'St. Kevin\'s College', 'Ballygall Rd. East', 'Finglas', 'Dublin 11', 'Dublin', role_numbers)
insert_into_role_numbers('70160R', 'St. Kevin\'s College', 'Clogher Road', 'Crumlin', 'Dublin 12', 'Dublin', role_numbers)
insert_into_role_numbers('70800E', 'St. Kevin\'s Community College', 'Dunlavin', '', '', 'Wicklow', role_numbers)
insert_into_role_numbers('70042L', 'St. Kevin\'s Community College', 'Fonthill Road', 'Clondalkin', 'Dublin 22', 'Dublin', role_numbers)
insert_into_role_numbers('61560J', 'St. Kieran\'s College', 'Secondary School', 'College Rd.', '', 'Kilkenny', role_numbers)
insert_into_role_numbers('91376L', 'St. Kilian\'s Community School', 'Ballywaltrim', 'Bray', '', 'Wicklow', role_numbers)
insert_into_role_numbers('60630W', 'St. Kilian\'s Deutsche Schule', 'Roebuck Rd.', 'Clonskeagh', 'Dublin 14', 'Dublin', role_numbers)
insert_into_role_numbers('60262T', 'St. Laurence College', 'Loughlinstown', 'Dublin 18', '', 'Dublin', role_numbers)
insert_into_role_numbers('61140K', 'St. Leo\'s College', 'Convent Of Mercy', 'Dublin Rd', '', 'Carlow', role_numbers)
insert_into_role_numbers('91494R', 'St. Louis Community School', 'Kiltimagh', '', '', 'Mayo', role_numbers)
insert_into_role_numbers('60890C', 'St. Louis High School', 'Charleville Rd.', 'Rathmines', 'Dublin 6', 'Dublin', role_numbers)
insert_into_role_numbers('63910U', 'St. Louis Secondary School', 'Dun Lughaidh', '', '', 'Louth', role_numbers)
insert_into_role_numbers('64760J', 'St. Louis Secondary School', 'Carrickmacross', '', '', 'Monaghan', role_numbers)
insert_into_role_numbers('64820B', 'St. Louis Secondary School', 'Glen Road', 'Monaghan Town', '', 'Monaghan', role_numbers)
insert_into_role_numbers('70260V', 'St. Mac Dara\'s Community College', 'Wellington Lane', 'Templeogue', 'Dublin 6W', 'Dublin', role_numbers)
insert_into_role_numbers('64810V', 'St. Macartan\'s College', 'Monaghan Town', '', '', 'Monaghan', role_numbers)
insert_into_role_numbers('91332O', 'St. Mark\'s Community School', 'Cookstown Rd.', 'Tallaght', 'Dublin 24', 'Dublin', role_numbers)
insert_into_role_numbers('61120E', 'St. Mary\'s Academy CBS', 'Station Rd.', 'Carlow Town', '', 'Carlow', role_numbers)
insert_into_role_numbers('63430G', 'St. Mary\'s CBS', 'Borris Road', 'Portlaoise', '', 'Laois', role_numbers)
insert_into_role_numbers('63560T', 'St. Mary\'s Christian Boys School', 'Millpark Road', 'Enniscorthy', '', 'Wexford', role_numbers)
insert_into_role_numbers('60560E', 'St. Mary\'s College', 'Rathmines', 'Dublin 6', '', 'Dublin', role_numbers)
insert_into_role_numbers('65130E', 'St. Mary\'s College', 'Ballysadare', '', '', 'Sligo', role_numbers)
insert_into_role_numbers('61780A', 'St. Mary\'s College', 'St Mary\'s Rd', 'Arklow', '', 'Wicklow', role_numbers)
insert_into_role_numbers('63890R', 'St. Mary\'s College', 'Dundalk', '', '', 'Louth', role_numbers)
insert_into_role_numbers('62980N', 'St. Mary\'s College', 'St. Mary\'s Road', 'Galway City', '', 'Galway', role_numbers)
insert_into_role_numbers('63841E', 'St. Mary\'s Diocesan School', 'Beamore Road', 'Drogheda', '', 'Louth', role_numbers)
insert_into_role_numbers('62380M', 'St. Mary\'s High School', 'Midleton', '', '', 'Cork', role_numbers)
insert_into_role_numbers('61130H', 'St. Mary\'s Knockbeg College', 'Knockbeg', '', '', 'Carlow', role_numbers)
insert_into_role_numbers('65400H', 'St. Mary\'s Secondary School', 'Newport', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('60021U', 'St. Mary\'s Secondary School', 'Baldoyle', 'Dublin 13', '', 'Dublin', role_numbers)
insert_into_role_numbers('62350D', 'St. Mary\'s Secondary School', 'Convent Of Mercy', 'Mallow', '', 'Cork', role_numbers)
insert_into_role_numbers('62320R', 'St. Mary\'s Secondary School', 'Convent Of Mercy', 'Macroom', '', 'Cork', role_numbers)
insert_into_role_numbers('60770P', 'St. Mary\'s Secondary School', 'Holy Faith Convent', 'Glasnevin', 'Dublin 11', 'Dublin', role_numbers)
insert_into_role_numbers('65582Q', 'St. Mary\'s Secondary School', 'Edenderry', '', '', 'Offaly', role_numbers)
insert_into_role_numbers('65380E', 'St. Mary\'s Secondary School', 'Nenagh', '', '', 'Tipperary', role_numbers)
insert_into_role_numbers('62450H', 'St. Mary\'s Secondary School', 'Convent Of Mercy', 'Charleville', '', 'Cork', role_numbers)
insert_into_role_numbers('64520M', 'St. Mary\'s Secondary School', 'Convent Hill,', 'Ballina', '', 'Mayo', role_numbers)
insert_into_role_numbers('63620L', 'St. Mary\'s Secondary School', 'Irishtown', 'New Ross', '', 'Wexford', role_numbers)
insert_into_role_numbers('63750B', 'St. Mel\'s College', 'St. Mel\'s Road', 'Longford Town', '', 'Longford', role_numbers)
insert_into_role_numbers('60561G', 'St. Michaels College', 'Ailesbury Rd.', 'Dublin 4', '', 'Dublin', role_numbers)
insert_into_role_numbers('61370E', 'St. Michael\'s College', 'Listowel', '', '', 'Kerry', role_numbers)
insert_into_role_numbers('70860W', 'St. Michael\'s Community College', 'Kilmihil', '', '', 'Clare', role_numbers)
insert_into_role_numbers('20279M', 'St. Michael\'s House Foxfield Special School', 'Briarfield Villas', 'Kilbarrack', 'Dublin 5', 'Dublin City', role_numbers)
insert_into_role_numbers('60741I', 'St. Michaels Secondary School', 'Wellmount Road', 'Finglas', 'Dublin 11', 'Dublin', role_numbers)
insert_into_role_numbers('70360C', 'St. Mogue\'s College', 'Bawnboy', '', '', 'Cavan', role_numbers)
insert_into_role_numbers('64240G', 'St. Munchin\'s College', 'Corbally', '', '', 'Limerick', role_numbers)
insert_into_role_numbers('64510J', 'St. Muredachs College', 'Sligo Road', 'Ballina', '', 'Mayo', role_numbers)
insert_into_role_numbers('68067P', 'St. Nathy\'s College', 'Ballaghaderreen', '', '', 'Roscommon', role_numbers)
insert_into_role_numbers('71920T', 'St. Nessan\'s Community College', 'Moylish Park', 'Moylish', 'Limerick City', 'Limerick', role_numbers)
insert_into_role_numbers('71990R', 'St. Oliver Post Primary', 'Oldcastle', 'Kells', '', 'Meath', role_numbers)
insert_into_role_numbers('71761C', 'St. Oliver\'s Community College', 'Rathmullen', 'Drogheda', '', 'Louth', role_numbers)
insert_into_role_numbers('60660I', 'St. Patrick\'s Cathedral G.S', 'St. Patrick\'s Close', 'Dublin 8', '', 'Dublin', role_numbers)
insert_into_role_numbers('64350N', 'St. Patrick\'s Classical School', 'Moatlands', 'Navan', '', 'Meath', role_numbers)
insert_into_role_numbers('62730N', 'St. Patrick\'s College', 'Gardiner\'s Hill', 'Cork City', '', 'Cork', role_numbers)
insert_into_role_numbers('61060M', 'St. Patrick\'s College', 'Cavan Town', '', '', 'Cavan', role_numbers)
insert_into_role_numbers('72130S', 'St. Patrick\'s College', 'Lacken Cross', 'Killala', '', 'Mayo', role_numbers)
insert_into_role_numbers('63101K', 'St. Pauls', 'Oughterard', '', '', 'Galway', role_numbers)
insert_into_role_numbers('72241E', 'St. Paul\'s  Community College', 'Browne\'s Road', 'Waterford City', '', 'Waterford', role_numbers)
insert_into_role_numbers('60430O', 'St. Paul\'s Christian Brothers School', 'Nth Brunswick Street', 'Dublin 7', '', 'Dublin', role_numbers)
insert_into_role_numbers('60290B', 'St. Paul\'s College', 'Sybil Hill', 'Raheny', 'Dublin 5', 'Dublin', role_numbers)
insert_into_role_numbers('60902G', 'St. Paul\'s Secondary School', 'Greenhills', 'Dublin 12', '', 'Dublin', role_numbers)
insert_into_role_numbers('61702D', 'St. Paul\'s Secondary School', 'Monasterevin', '', '', 'Kildare', role_numbers)
insert_into_role_numbers('71950F', 'St. Peter\'s College', 'Dunboyne', '', '', 'Meath', role_numbers)
insert_into_role_numbers('63650U', 'St. Peter\'s College Secondary School', 'Summerhill', '', '', 'Wexford', role_numbers)
insert_into_role_numbers('91391H', 'St. Peter\'s Community School', 'Passage West', '', '', 'Cork', role_numbers)
insert_into_role_numbers('60361V', 'St. Raphaela\'s Secondary School', 'Upper Kilmacud Road', 'Stillorgan', '', 'Dublin', role_numbers)
insert_into_role_numbers('63070C', 'St. Raphael\'s College', 'Loughrea', '', '', 'Galway', role_numbers)
insert_into_role_numbers('70770V', 'St. Thomas\' Community College', 'Novara Avenue', 'Bray', '', 'Wicklow', role_numbers)
insert_into_role_numbers('72100J', 'St. Tiernan\'s College', 'Crossmolina', 'Ballina', '', 'Mayo', role_numbers)
insert_into_role_numbers('91343T', 'St. Tiernan\'s Community School', 'Parkvale', 'Balally', 'Dublin 16', 'Dublin', role_numbers)
insert_into_role_numbers('60400F', 'St. Vincent\'s Christian Boys School', 'Glasnevin', 'Dublin 11', '', 'Dublin', role_numbers)
insert_into_role_numbers('62590A', 'St. Vincent\'s Secondary School', 'St. Mary\'s Road', 'Blackpool', 'Cork City', 'Cork', role_numbers)
insert_into_role_numbers('63900R', 'St. Vincent\'s Secondary School', 'Seatown Place', 'Dundalk', '', 'Louth', role_numbers)
insert_into_role_numbers('91505T', 'St. Wolstan\'s Community School', 'Ballymakeely', 'Clane Rd', 'Celbridge', 'Kildare', role_numbers)
insert_into_role_numbers('64922J', 'Stella Maris', 'Pond Rd', 'Tramore', '', 'Waterford', role_numbers)
insert_into_role_numbers('61020A', 'Stratford College', '1 Zion Road', 'Rathgar', 'Dublin 6', 'Dublin', role_numbers)
insert_into_role_numbers('65170Q', 'Summerhill College', 'College Rd.', 'Sligo Town', '', 'Sligo', role_numbers)
insert_into_role_numbers('60381E', 'Sutton Park School', 'St. Fintan\'s Rd.', 'Sutton', 'Dublin 13', 'Dublin', role_numbers)
insert_into_role_numbers('60470D', 'Synge St. C.B.S.', 'Synge St.', 'Dublin 8', '', 'Dublin', role_numbers)
insert_into_role_numbers('91335U', 'Tallaght Community School', 'Balrothery', 'Tallaght', 'Dublin 24', 'Dublin', role_numbers)
insert_into_role_numbers('71730O', 'Templemichael College', 'Longford Town', '', '', 'Longford', role_numbers)
insert_into_role_numbers('60562I', 'Templeogue College', 'Templeville Rd.', 'Dublin 6', '', 'Dublin', role_numbers)
insert_into_role_numbers('71123Q', 'Terence MacSwiney Community College', 'Hollyhill', 'Knocknaheeny', 'Cork City', 'Cork City', role_numbers)
insert_into_role_numbers('60570H', 'Terenure College', 'Templeogue Rd.', 'Terenure', 'Dublin 6W', 'Dublin', role_numbers)
insert_into_role_numbers('65490L', 'The Abbey School', 'Station Rd.', 'Tipperary Town', '', 'Tipperary', role_numbers)
insert_into_role_numbers('91318U', 'The Donahies Community School', 'Streamville Rd.', 'Dublin 13', '', 'Dublin', role_numbers)
insert_into_role_numbers('60670L', 'The High School', 'Zion Rd.', 'Rathgar', 'Dublin 6', 'Dublin', role_numbers)
insert_into_role_numbers('61360B', 'The Intermediate School', 'Iveragh Rd.', 'Killorglin', '', 'Kerry', role_numbers)
insert_into_role_numbers('60272W', 'The Kings Hospital', 'Palmerstown', 'Dublin 20', '', 'Dublin', role_numbers)
insert_into_role_numbers('81011L', 'The Royal And Prior School', 'Raphoe', '', '', 'Donegal', role_numbers)
insert_into_role_numbers('60892G', 'The Teresian School', '12 Stillorgan Rd.', 'Donnybrook', 'Dublin 4', 'Dublin', role_numbers)
insert_into_role_numbers('70550H', 'Tralee Community College', 'Clash', 'Tralee', '', 'Kerry', role_numbers)
insert_into_role_numbers('81017A', 'Trinity Comprehensive School', 'Ballymun Rd.', 'Dublin 9', '', 'Dublin', role_numbers)
insert_into_role_numbers('72560U', 'Tullamore College', 'Riverside', 'Tullamore', '', 'Offaly', role_numbers)
insert_into_role_numbers('91356F', 'Tullow Community School', 'The Mullawn', 'Tullow', '', 'Carlow', role_numbers)
insert_into_role_numbers('65180T', 'Ursuline College', 'Finisklin Rd.', 'Finisklin', '', 'Sligo', role_numbers)
insert_into_role_numbers('62650P', 'Ursuline Secondary School', 'Blackrock', 'Cork City', '', 'Cork', role_numbers)
insert_into_role_numbers('65470F', 'Ursuline Secondary School', 'Templemore Road', 'Thurles', '', 'Tipperary', role_numbers)
insert_into_role_numbers('64310B', 'Villiers Secondary School', 'North Circular Road', 'Limerick City', '', 'Limerick', role_numbers)
insert_into_role_numbers('70390L', 'Virginia College', 'Virginia', '', '', 'Cavan', role_numbers)
insert_into_role_numbers('71620H', 'Vocational College Bunclody', 'Bunclody', 'Enniscorthy', '', 'Wexford', role_numbers)
insert_into_role_numbers('71570S', 'Vocational School', 'Drumshanbo', '', '', 'Leitrim', role_numbers)
insert_into_role_numbers('70430U', 'Vocational School', 'Muine Bheag', 'Carlow Town', '', 'Carlow', role_numbers)
insert_into_role_numbers('64940L', 'Waterpark College', 'Park Road', 'Waterford', '', 'Waterford', role_numbers)
insert_into_role_numbers('61010U', 'Wesley College', 'Ballinteer', 'Dublin 16', '', 'Dublin', role_numbers)
insert_into_role_numbers('71680C', 'Wexford Vocational College', 'Westgate', 'Wexford Town', '', 'Wexford', role_numbers)
insert_into_role_numbers('63300Q', 'Wilson\'s Hospital School', 'Multyfarnham', '', '', 'Westmeath', role_numbers)